/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_EmbedC */

#ifndef _Included_com_EmbedC
#define _Included_com_EmbedC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_EmbedC
 * Method:    callEmbed
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_EmbedC_callEmbed
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
